'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da uno strumento.
'
'     Le modifiche a questo file possono causare un comportamento non corretto e verranno perse se
'     il codice viene rigenerato.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class Register

    '''<summary>
    '''Controllo RegisterUser.
    '''</summary>
    '''<remarks>
    '''Campo generato automaticamente.
    '''Per la modifica, spostare la dichiarazione di campo dal file di progettazione al file code-behind.
    '''</remarks>
    Protected WithEvents RegisterUser As Global.System.Web.UI.WebControls.CreateUserWizard

    '''<summary>
    '''Controllo RegisterUserWizardStep.
    '''</summary>
    '''<remarks>
    '''Campo generato automaticamente.
    '''Per la modifica, spostare la dichiarazione di campo dal file di progettazione al file code-behind.
    '''</remarks>
    Protected WithEvents RegisterUserWizardStep As Global.System.Web.UI.WebControls.CreateUserWizardStep
End Class
